# Generated by Django 2.2.1 on 2019-07-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDie', models.PositiveIntegerField()),
                ('index_x', models.PositiveIntegerField()),
                ('index_y', models.PositiveIntegerField()),
                ('size_x', models.PositiveIntegerField()),
                ('size_y', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMarco', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModule', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Marco')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTechnology', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('wds', models.CharField(max_length=64)),
                ('wafer_counts', models.PositiveIntegerField()),
                ('f51_file_path', models.FilePathField(path=None)),
                ('f11_file_path', models.FilePathField(path=None)),
                ('dm_file_path', models.FilePathField(path=None)),
            ],
        ),
        migrations.CreateModel(
            name='Wafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idWafer', models.PositiveIntegerField()),
                ('lot', models.CharField(max_length=64)),
                ('wafer_number', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('orientation', models.CharField(max_length=64)),
                ('part', models.CharField(max_length=64)),
                ('row_counts', models.PositiveIntegerField()),
                ('column_counts', models.PositiveIntegerField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='TestStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestStructure', models.CharField(default='default', max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(default='default', max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Module')),
            ],
        ),
        migrations.CreateModel(
            name='TestChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestChip', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Die')),
            ],
        ),
        migrations.AddField(
            model_name='marco',
            name='testChip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.TestChip'),
        ),
        migrations.AddField(
            model_name='die',
            name='wafer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Wafer'),
        ),
    ]
