# Generated by Django 2.2.1 on 2019-08-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestStructure', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Module')),
            ],
        ),
        migrations.RenameModel(
            old_name='TestChip',
            new_name='Chip',
        ),
        migrations.RenameModel(
            old_name='Die',
            new_name='Reticle',
        ),
        migrations.DeleteModel(
            name='TestStructure',
        ),
    ]
