# Generated by Django 2.2.1 on 2019-08-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190807_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTC', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TestMarco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestMarco', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
                ('testChip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestChip')),
            ],
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestModule', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
                ('testMarco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestMarco')),
            ],
        ),
        migrations.RenameField(
            model_name='chip',
            old_name='idTestChip',
            new_name='idChip',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='idTestStructure',
            new_name='idDevice',
        ),
        migrations.RenameField(
            model_name='reticle',
            old_name='idDie',
            new_name='idReticle',
        ),
        migrations.AlterField(
            model_name='reticle',
            name='wafer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Wafer'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Technology'),
        ),
        migrations.CreateModel(
            name='TestStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTestStructure', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
                ('testModule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestModule')),
            ],
        ),
        migrations.AddField(
            model_name='chip',
            name='testChip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestChip'),
        ),
        migrations.AddField(
            model_name='device',
            name='testStructure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestStructure'),
        ),
        migrations.AddField(
            model_name='marco',
            name='testMarco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestMarco'),
        ),
        migrations.AddField(
            model_name='module',
            name='testModule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.TestModule'),
        ),
    ]
