# Generated by Django 2.2.1 on 2019-08-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190807_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chip',
            old_name='die',
            new_name='reticle',
        ),
        migrations.RenameField(
            model_name='marco',
            old_name='testChip',
            new_name='chip',
        ),
    ]
