# Generated by Django 2.2.1 on 2019-08-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190808_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marco',
            name='name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='name',
        ),
    ]
