# Generated by Django 2.2.1 on 2019-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190823_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='idDevice',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='marco',
            name='idMarco',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='module',
            name='idModule',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reticle',
            name='idReticle',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='technology',
            name='idTechnology',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testchip',
            name='idTC',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testmarco',
            name='idTestMarco',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='idTestModule',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='idWafer',
            field=models.CharField(max_length=64),
        ),
    ]
