# Generated by Django 2.2.1 on 2019-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_overview_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='file_path',
            field=models.FilePathField(null=True, path='home'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='file_path',
            field=models.FilePathField(null=True, path='home'),
        ),
    ]
