# Generated by Django 2.2.1 on 2019-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20191017_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='file_path',
            field=models.FilePathField(null=True, path='\\mucsdn32\\RM\\mw'),
        ),
    ]
