# Generated by Django 2.2.1 on 2019-10-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20191017_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='excel_file',
            field=models.URLField(null=True),
        ),
    ]
