# Generated by Django 2.2.1 on 2019-10-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20191017_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='excel_file',
        ),
    ]
