# Generated by Django 2.2.1 on 2019-10-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20191017_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Technology')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='overview',
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
    ]
