# Generated by Django 2.2.1 on 2019-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20191023_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='failCriterion',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='maxLeakage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
