# Generated by Django 2.2.1 on 2019-10-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_auto_20191023_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
