# Generated by Django 2.2.1 on 2019-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_protocol_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='prober',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
