# Generated by Django 2.2.1 on 2019-10-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_auto_20191024_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='readouts',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
