# Generated by Django 2.2.1 on 2019-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_protocol_readouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='receiveDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='topic',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
